const ADD_FOUNDATION = 'ADD_FOUNDATION';
const RESET_FOUNDATIONS = 'RESET_FOUNDATIONS';
const CLEAR = "Clear list";
const SET_CURRENT_FUNDATION = "Set current fundation"

export default {
    ADD_FOUNDATION,
    RESET_FOUNDATIONS,
    CLEAR,
    SET_CURRENT_FUNDATION
};